
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 04 11:32:05 CEST 2012
//----------------------------------------------------

package translator;

/** CUP generated interface containing symbol constants. */
public interface TranslatorPy2JSym {
  /* terminals */
  public static final int AT = 70;
  public static final int AS = 3;
  public static final int ANDEQ = 76;
  public static final int FROM = 18;
  public static final int LCURLY = 61;
  public static final int HEX = 83;
  public static final int NEWLINE = 31;
  public static final int PLUSEQ = 71;
  public static final int RAISE = 36;
  public static final int SEMI = 56;
  public static final int LAMBDA = 24;
  public static final int TRIDOT = 29;
  public static final int NAME = 88;
  public static final int PASS = 27;
  public static final int EXPEQ = 78;
  public static final int INDENT = 33;
  public static final int RBRACK = 60;
  public static final int COMMA = 55;
  public static final int DEDENT = 34;
  public static final int OCT = 84;
  public static final int ELIF = 10;
  public static final int RPAREN = 64;
  public static final int LBRACK = 59;
  public static final int LPAREN = 63;
  public static final int DEL = 9;
  public static final int MAIEQ = 52;
  public static final int YIELD = 28;
  public static final int NOT = 25;
  public static final int TILDE = 65;
  public static final int DEF = 8;
  public static final int FLOAT = 86;
  public static final int MINEQ = 50;
  public static final int EQ = 53;
  public static final int MULTMULT = 32;
  public static final int MOD = 46;
  public static final int CLASS = 6;
  public static final int EXCEPT = 12;
  public static final int PIPE = 67;
  public static final int ECOM = 66;
  public static final int PLUS = 42;
  public static final int DIVIDE = 45;
  public static final int EXEC = 13;
  public static final int WHILE = 39;
  public static final int DECIMAL = 81;
  public static final int ASSIGN = 57;
  public static final int LONGINT = 82;
  public static final int FOR = 17;
  public static final int EXPON = 47;
  public static final int RETURN = 37;
  public static final int MULT = 44;
  public static final int ELSE = 11;
  public static final int TRY = 38;
  public static final int BREAK = 5;
  public static final int DOT = 48;
  public static final int MAIOR = 51;
  public static final int EOF = 0;
  public static final int COMMENT = 14;
  public static final int BIN = 85;
  public static final int PRINT = 35;
  public static final int MULTEQ = 73;
  public static final int MINOR = 49;
  public static final int IMPORT = 21;
  public static final int IS = 23;
  public static final int MINUS = 43;
  public static final int DIVDIV = 30;
  public static final int IN = 22;
  public static final int OR = 26;
  public static final int error = 1;
  public static final int LSEQ = 80;
  public static final int DIVEQ = 74;
  public static final int FINALLY = 16;
  public static final int WHITESPACE = 15;
  public static final int CONTINUE = 7;
  public static final int IF = 20;
  public static final int MODEQ = 75;
  public static final int COLON = 58;
  public static final int ASSERT = 4;
  public static final int OREQ = 77;
  public static final int GLOBAL = 19;
  public static final int STRING = 89;
  public static final int RSHIFT = 69;
  public static final int RANGE = 41;
  public static final int RSEQ = 79;
  public static final int IMAGNUM = 87;
  public static final int NEQ = 54;
  public static final int AND = 2;
  public static final int LSHIFT = 68;
  public static final int WITH = 40;
  public static final int RCURLY = 62;
  public static final int MINUSEQ = 72;
}

